// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ZV4XsAVc1Jqt6U70wcqe6LxumlxOng0',
    appId: '1:423460276753:web:819292faad732e45b27fb0',
    messagingSenderId: '423460276753',
    projectId: 'todolist-app-361d5',
    authDomain: 'todolist-app-361d5.firebaseapp.com',
    storageBucket: 'todolist-app-361d5.appspot.com',
    measurementId: 'G-V2HHCHKZDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYrMHeVoNKviV6I6F_EPvLgVab16aV9ZI',
    appId: '1:423460276753:android:c436f9e3e89e7aa8b27fb0',
    messagingSenderId: '423460276753',
    projectId: 'todolist-app-361d5',
    storageBucket: 'todolist-app-361d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nynR2G4o20NZ1l-phmlJw9IF7Z52bzI',
    appId: '1:423460276753:ios:0efa8dba663212d3b27fb0',
    messagingSenderId: '423460276753',
    projectId: 'todolist-app-361d5',
    storageBucket: 'todolist-app-361d5.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nynR2G4o20NZ1l-phmlJw9IF7Z52bzI',
    appId: '1:423460276753:ios:9117851e4bbf53ffb27fb0',
    messagingSenderId: '423460276753',
    projectId: 'todolist-app-361d5',
    storageBucket: 'todolist-app-361d5.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
